/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BiteIndexMap: typeof import('./src/components/BiteIndexMap/index.vue')['default']
    Components: typeof import('./src/components/index.vue')['default']
    CurrentStateLayer: typeof import('./src/components/BiteIndexMap/CurrentStateLayer.vue')['default']
    Legend: typeof import('./src/components/BiteIndexMap/Legend.vue')['default']
    MainDrawer: typeof import('./src/components/MainDrawer.vue')['default']
    MainHeader: typeof import('./src/components/MainHeader.vue')['default']
    MapLegend: typeof import('./src/components/BiteIndexMap/MapLegend.vue')['default']
    PlaybackControl: typeof import('./src/components/PlaybackControl.vue')['default']
    PlaybackMap: typeof import('./src/components/PlaybackMap/index.vue')['default']
    RegionAnomaliesHistoryTable: typeof import('./src/components/BiteIndexMap/RegionDetailedDrawer/RegionDetailExtraDrawer/RegionAnomaliesHistoryTable.vue')['default']
    RegionDetailedDrawer: typeof import('./src/components/BiteIndexMap/RegionDetailedDrawer/index.vue')['default']
    RegionDetailExtraDrawer: typeof import('./src/components/BiteIndexMap/RegionDetailedDrawer/RegionDetailExtraDrawer/index.vue')['default']
    RegionDetailTableDrawer: typeof import('./src/components/BiteIndexMap/RegionDetailedDrawer/RegionDetailTableDrawer/index.vue')['default']
    RegionSeasonality: typeof import('./src/components/BiteIndexMap/RegionDetailedDrawer/RegionSeasonality.vue')['default']
    RegionSummary: typeof import('./src/components/BiteIndexMap/RegionDetailedDrawer/RegionSummary.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBox: typeof import('./src/components/BiteIndexMap/SearchBox.vue')['default']
    TimeSeriesChart: typeof import('./src/components/BiteIndexMap/RegionDetailedDrawer/TimeSeriesChart.vue')['default']
  }
}
